# -*- coding: utf-8 -*-
"""Ploting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkDUXw2kykFGd7dPAl01dnmDe37QUAVn
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install pandas
!pip install matplotlib

import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/EDA_dataset.xlsx")
plt.figure(figsize=(12,8))
x=list(df['Age'])

y=list(df['Spending_Score (1-100)'])

plt.xlabel('Age')

plt.hist(x,ec='black',color='red',alpha=0.5)
plt.hist(y,ec='black',color='yellow',alpha=0.2)
plt.xlabel('Age')
plt.ylabel('Spending_score')
plt.title('Age vs Annual_Income (k$)')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/EDA_dataset.xlsx")
plt.figure(figsize=(12, 8))
x=(df['Annual_Income (k$)'])
y=(df['Spending_Score (1-100)'])
colors = np.arange(1,101)
plt.scatter(x,y,c=colors,cmap='viridis',marker='*')
plt.title('Scatter Plot of Annual Income vs Spending Score')
plt.colorbar(label='Spending Score')
plt.xlabel('Annual_Income (k$)')
plt.ylabel('Spending_Score (1-100)')

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
plt.figure(figsize=(12, 8))
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/EDA_dataset.xlsx")
a=list(df['Gender'])
b=list(df['Product_Purchased'])
data=(a,b)
sns.heatmap(pd.crosstab(a,b),annot=True,cmap='YlGnBu')
plt.ylabel('Gender')
plt.xlabel('Age')
plt.title('Gender vs Product_Purchased')
plt.show()